cat <<EOF > /tmp/ConfigureSNOW.py
from selenium import webdriver
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.action_chains import ActionChains
import os, sys, time

options = Options()
options.headless = True
profile = webdriver.FirefoxProfile()
browser = webdriver.Firefox(options=options,firefox_profile=profile)

# Service Now instance id need to be changes in the url
snow_url = "https://@@{SNOWInstanceURL}@@/nav_to.do?"
snow_username = "admin"
snow_password = "@@{SNOWAdminPassword}@@"
snow_users = "https://@@{SNOWInstanceURL}@@/sys_user_list.do?sysparm_userpref_module%3Dc5aa0fff0a0a0aa7009a39da035ea396%26sysparm_clear_stack%3Dtrue"
snow_groups = "https://@@{SNOWInstanceURL}@@/sys_user_group_list.do?sysparm_userpref_module%3Dc5aa68730a0a0aa70036ced8b58ca05c%26sysparm_clear_stack%3Dtrue"
user_criteria_plugin_url = "https://@@{SNOWInstanceURL}@@/\$allappsmgmt.do?sysparm_redirect%3Dtrue&sysparm_search=User%20Criteria%20Scoped%20API"
glide_validate_property_url = "https://@@{SNOWInstanceURL}@@/sys_properties_list.do?sysparm_query=nameSTARTSWITHglide.sc.guide.tab.validate&sysparm_first_row=1&sysparm_view=&sysparm_choice_query_raw=&sysparm_list_header_search=true"
glide_reset_cascade_url = "https://@@{SNOWInstanceURL}@@/sys_properties_list.do?sysparm_query=nameSTARTSWITHglide.sc.reset_cascade&sysparm_first_row=1&sysparm_view=&sysparm_choice_query_raw=&sysparm_list_header_search=true"
tables_url = "https://@@{SNOWInstanceURL}@@/sys_db_object_list.do?sysparm_query=labelSTARTSWITHCatalog%20Client%20Scripts&sysparm_first_row=1&sysparm_view=&sysparm_choice_query_raw=&sysparm_list_header_search=true"

sys_property = "sys_properties.list"
property_name = "glide.sc.guide.tab.validate"

###Login to the ServiceNow Instance
browser.get(snow_url)
time.sleep(30)
#frame = browser.find_element_by_xpath
browser.switch_to.frame('gsft_main')
time.sleep(5)
browser.find_element_by_id("user_name").send_keys(snow_username)
browser.find_element_by_id("user_password").send_keys(snow_password)
browser.find_element_by_id("sysverb_login").click()
print('Logged in to SNOW')
browser.switch_to_default_content()

##Upload & Install build (v1.0+1.1)
browser.get(snow_url)
time.sleep(30)
browser.find_element_by_id("filter").send_keys("sys_remote_update_set_list.do")
browser.find_element_by_id("filter").send_keys(Keys.ENTER)
time.sleep(10)
browser.switch_to.frame('gsft_main')
time.sleep(10)
browser.find_element_by_link_text("Nutanix Calm").click()
browser.implicitly_wait(10)
try:
    browser.find_element_by_id("preview_update_set").click()
    browser.implicitly_wait(180)
    browser.find_element_by_xpath("//*[@id='sysparm_button_close']").click()
    browser.implicitly_wait(10)
except:
  	print('Update set preview already run')
try:
    browser.find_element_by_link_text("Skip remote update").click()
    browser.implicitly_wait(10)
    browser.find_element_by_link_text("Skip remote update").click()
    browser.implicitly_wait(10)
    browser.find_element_by_link_text("Skip remote update").click()
    browser.implicitly_wait(10)
    browser.find_element_by_link_text("Skip remote update").click()
    browser.implicitly_wait(10)
    browser.find_element_by_link_text("Skip remote update").click()
    browser.implicitly_wait(10)
except:
  	print('Skip remote update not there, committing update set')
browser.find_element_by_xpath("//*[@id='c38b2cab0a0a0b5000470398d9e60c36']").click()
browser.implicitly_wait(600)
browser.find_element_by_xpath("//*[@id='sysparm_button_close']").click()
browser.implicitly_wait(10)
print('Calm v1.1 plugin installed')
browser.switch_to_default_content()

######Upload & Install build (v1.2_5)
browser.get(snow_url)
time.sleep(30)
browser.find_element_by_id("filter").send_keys("sys_remote_update_set_list.do")
browser.find_element_by_id("filter").send_keys(Keys.ENTER)
time.sleep(5)
browser.switch_to.frame('gsft_main')
time.sleep(5)
browser.find_element_by_link_text("Import Update Set from XML").click()
time.sleep(5)
browser.find_element_by_xpath("//*[@id='attachFile']").send_keys("/tmp/Nutanix Calm V1.2_5.xml")
browser.implicitly_wait(10)
browser.find_element_by_xpath("/html/body/div[2]/form/div[3]/div[2]/input").click()
browser.implicitly_wait(300)
browser.find_element_by_link_text("Nutanix Calm V1.2_5").click()
browser.implicitly_wait(5)
browser.find_element_by_id("preview_update_set").click()
browser.implicitly_wait(90)
browser.find_element_by_xpath("//*[@id='sysparm_button_close']").click()
browser.implicitly_wait(10)
try:
    browser.find_element_by_link_text("Skip remote update").click()
    browser.implicitly_wait(10)
except:
  	print('Skip remote update not there')
browser.find_element_by_xpath("//*[@id='c38b2cab0a0a0b5000470398d9e60c36']").click()
browser.implicitly_wait(600)
browser.find_element_by_xpath("//*[@id='sysparm_button_close']").click()
print('Calm v1.2.5 plugin installed')
browser.switch_to_default_content()

######Upload & Install build (v1.3_4)
browser.get(snow_url)
time.sleep(30)
browser.find_element_by_id("filter").send_keys("sys_remote_update_set_list.do")
browser.find_element_by_id("filter").send_keys(Keys.ENTER)
time.sleep(5)
browser.switch_to.frame('gsft_main')
time.sleep(5)
browser.find_element_by_link_text("Import Update Set from XML").click()
time.sleep(5)
browser.find_element_by_xpath("//*[@id='attachFile']").send_keys("/tmp/Nutanix Calm V1.3_4.xml")
browser.implicitly_wait(10)
browser.find_element_by_xpath("/html/body/div[2]/form/div[3]/div[2]/input").click()
browser.implicitly_wait(300)
browser.find_element_by_link_text("Nutanix Calm V1.3_4").click()
browser.implicitly_wait(5)
browser.find_element_by_id("preview_update_set").click()
browser.implicitly_wait(90)
browser.find_element_by_xpath("//*[@id='sysparm_button_close']").click()
browser.implicitly_wait(10)
browser.find_element_by_xpath("//*[@id='c38b2cab0a0a0b5000470398d9e60c36']").click()
browser.implicitly_wait(600)
browser.find_element_by_xpath("//*[@id='sysparm_button_close']").click()
print('Calm v1.3.4 plugin installed')
browser.switch_to_default_content()

###glide.sc.reset_cascade Property Change
browser.get(glide_reset_cascade_url)
time.sleep(30)
browser.find_element_by_link_text("glide.sc.reset_cascade").click()
time.sleep(10)
browser.find_element_by_id("sys_properties.value").clear()
browser.find_element_by_id("sys_properties.value").send_keys("true")
browser.find_element_by_id("sysverb_update").click()
time.sleep(15)
print('glide.sc.reset_cascade updated')

###Table permission update
#browser.get(tables_url)
#time.sleep(30)
#browser.find_element_by_link_text("Catalog Client Scripts").click()
#time.sleep(5)
#browser.find_element_by_xpath("//*[@id='tabs2_section']/span[3]/span[1]/span[2]").click()
#time.sleep(5)
#browser.find_element_by_xpath("//*[@id='label.ni.sys_db_object.update_access']").click()
#time.sleep(5)
#browser.find_element_by_id("sysverb_update").click()
#time.sleep(5)
#print('Catalog Client Scripts permissions updated')

######Upload & Install build (v1.4.22)
browser.get(snow_url)
time.sleep(30)
browser.find_element_by_id("filter").send_keys("sys_remote_update_set_list.do")
browser.find_element_by_id("filter").send_keys(Keys.ENTER)
time.sleep(5)
browser.switch_to.frame('gsft_main')
time.sleep(5)
browser.find_element_by_link_text("Import Update Set from XML").click()
time.sleep(5)
browser.find_element_by_xpath("//*[@id='attachFile']").send_keys("/tmp/Nutanix Calm V1.4.2.xml")
browser.implicitly_wait(10)
browser.find_element_by_xpath("/html/body/div[2]/form/div[3]/div[2]/input").click()
browser.implicitly_wait(300)
browser.find_element_by_link_text("Nutanix Calm V1.4.2").click()
browser.implicitly_wait(5)
browser.find_element_by_id("preview_update_set").click()
browser.implicitly_wait(90)
browser.find_element_by_xpath("//*[@id='sysparm_button_close']").click()
browser.implicitly_wait(10)
#browser.find_element_by_link_text("Skip remote update").click()
#browser.implicitly_wait(10)
browser.find_element_by_xpath("//*[@id='c38b2cab0a0a0b5000470398d9e60c36']").click()
browser.implicitly_wait(10)
browser.find_element_by_xpath("//*[@id='ok_button']").click()
browser.implicitly_wait(300)
browser.find_element_by_xpath("//*[@id='sysparm_button_close']").click()
print('Calm v1.4.2 plugin installed')
browser.switch_to_default_content()

######Upload & Install build (v1.4.3)
browser.get(snow_url)
time.sleep(30)
browser.find_element_by_id("filter").send_keys("sys_remote_update_set_list.do")
browser.find_element_by_id("filter").send_keys(Keys.ENTER)
time.sleep(5)
browser.switch_to.frame('gsft_main')
time.sleep(5)
browser.find_element_by_link_text("Import Update Set from XML").click()
time.sleep(5)
browser.find_element_by_xpath("//*[@id='attachFile']").send_keys("/tmp/Nutanix Calm V1.4.3.xml")
browser.implicitly_wait(10)
browser.find_element_by_xpath("/html/body/div[2]/form/div[3]/div[2]/input").click()
browser.implicitly_wait(300)
browser.find_element_by_link_text("Nutanix Calm V1.4.3").click()
browser.implicitly_wait(5)
browser.find_element_by_id("preview_update_set").click()
browser.implicitly_wait(90)
browser.find_element_by_xpath("//*[@id='sysparm_button_close']").click()
browser.implicitly_wait(10)
browser.find_element_by_xpath("//*[@id='c38b2cab0a0a0b5000470398d9e60c36']").click()
browser.implicitly_wait(300)
browser.find_element_by_xpath("//*[@id='sysparm_button_close']").click()
print('Calm v1.4.3 plugin installed')
browser.switch_to_default_content()

######Upload & Install "Nutanix Calm - User Approval" Workflow
browser.get(snow_url)
time.sleep(30)
browser.find_element_by_id("filter").send_keys("sys_remote_update_set_list.do")
browser.find_element_by_id("filter").send_keys(Keys.ENTER)
time.sleep(5)
browser.switch_to.frame('gsft_main')
time.sleep(5)
browser.find_element_by_link_text("Import Update Set from XML").click()
time.sleep(5)
browser.find_element_by_xpath("//*[@id='attachFile']").send_keys("/tmp/Nutanix Calm User Approval Workflow 1.0.xml")
browser.implicitly_wait(10)
browser.find_element_by_xpath("/html/body/div[2]/form/div[3]/div[2]/input").click()
browser.implicitly_wait(300)
browser.find_element_by_link_text("User Approval Workflow").click()
browser.implicitly_wait(5)
browser.find_element_by_id("preview_update_set").click()
browser.implicitly_wait(90)
browser.find_element_by_xpath("//*[@id='sysparm_button_close']").click()
browser.implicitly_wait(10)
browser.find_element_by_xpath("//*[@id='c38b2cab0a0a0b5000470398d9e60c36']").click()
browser.implicitly_wait(300)
browser.find_element_by_xpath("//*[@id='sysparm_button_close']").click()
print('User Approval Workflow installed')
browser.switch_to_default_content()

#Create Calm Users group
browser.get(snow_groups)
time.sleep(30)
browser.find_element_by_id("sysverb_new").click()
time.sleep(5)
browser.find_element_by_xpath("//*[@id='sys_user_group.name']").send_keys("Calm Users")
browser.find_element_by_xpath("//*[@id='sysverb_insert']").click()
time.sleep(5)
browser.find_element_by_link_text("Calm Users").click()
time.sleep(5)
browser.find_element_by_id("sysverb_edit_m2m").click()
time.sleep(5)
browser.find_element_by_id("_sys_user_role").send_keys("x_nuta2_nutanix_ca.user")
time.sleep(5)
browser.find_element_by_xpath("//*[text()='x_nuta2_nutanix_ca.user']").click()
time.sleep(5)
browser.find_element_by_id("add_to_collection_button").click()
time.sleep(5)
browser.find_element_by_id("select_0_sysverb_save").click()
time.sleep(5)
browser.find_element_by_id("sysverb_update").click()
time.sleep(5)
print('Calm Users group created')

#Create Nutanix Calm users
browser.get(snow_users)
time.sleep(30)
for x in range(1, 11):
    name = "operator{}".format('%02d' % x)

    browser.find_element_by_id("sysverb_new").click()
    time.sleep(5)
    browser.find_element_by_xpath("//*[@id='sys_user.user_name']").send_keys(name)
    browser.find_element_by_xpath("//*[@id='sys_user.user_password']").send_keys("nutanix/4u")
    browser.find_element_by_xpath("//*[@id='sysverb_insert']").click()
    time.sleep(5)
    browser.find_element_by_link_text(name).click()
    time.sleep(5)
    browser.find_element_by_xpath("//*[@id='tabs2_list']/span[3]/span/span[2]").click()
    time.sleep(3)
    browser.find_element_by_xpath("/html/body/div[2]/div[2]/div/div[3]/span/div[2]/div[1]/div/div[1]/button[3]").click()
    time.sleep(5)
    browser.find_element_by_id("_sys_user_group").send_keys("Calm Users")
    time.sleep(5)
    browser.find_element_by_xpath("//*[text()='Calm Users']").click()
    time.sleep(5)
    browser.find_element_by_id("add_to_collection_button").click()
    time.sleep(5)
    browser.find_element_by_id("select_0_sysverb_save").click()
    time.sleep(5)
    browser.find_element_by_id("sysverb_update").click()
    time.sleep(10)
    print('{} user account created'.format(name))

######End
browser.quit()
EOF
wget -P /tmp/ https://raw.githubusercontent.com/nutanix/Calm-Servicenow-Plugin/master/v1.1/Nutanix%20Full%20Certified%20Build\(v1.0%2Bv1.1\).xml
wget -P /tmp/ https://raw.githubusercontent.com/nutanix/Calm-Servicenow-Plugin/master/v1.2/Nutanix%20Calm%20V1.2_5.xml
wget -P /tmp/ https://raw.githubusercontent.com/nutanixworkshops/gts21/master/snow/plugins/Nutanix%20Calm%20V1.3_4.xml
wget -P /tmp/ https://raw.githubusercontent.com/nutanixworkshops/gts21/master/snow/plugins/Nutanix%20Calm%20V1.4.2.xml
wget -P /tmp/ https://raw.githubusercontent.com/nutanixworkshops/gts21/master/snow/plugins/Nutanix%20Calm%20V1.4.3.xml
wget -P /tmp/ https://raw.githubusercontent.com/nutanixworkshops/gts21/master/snow/plugins/Nutanix%20Calm%20User%20Approval%20Workflow%201.0.xml
python3 /tmp/ConfigureSNOW.py
